### ISSUE TITLE
Modification of the VGG16 network

### ISSUE THREAD

**Issue by amlandas78** [DebasmitaGhose/Multimodal_Influenza_Detection#2]
@DebasmitaGhose Previously I was using a tensorflow implementation of the Faster RCNN network where I could easily freeze the convolutional layers. I am very much new to pytorch. Can you please tell me how to freeze the convolutional layers in the VGG16 network?

**Comment by immuno121** [comment]
Hi,
You can do it in the following manner.
for param in model.parameters():
    param.requires_grad = False
